"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.listOrdersHandler = exports.getOrderHandler = exports.createOrderHandler = void 0;
const orderModel_1 = require("../models/orderModel");
const cartModel_1 = require("../models/cartModel");
const userModel_1 = require("../models/userModel");
const dbConnection_1 = __importDefault(require("../utils/dbConnection"));
/**
 * Handles creating an order from the user's cart.
 * @param req Request object with authenticated user ID
 * @param res Response object to send the order data
 * @param next Next function for error handling
 */
const createOrderHandler = async (req, res, next) => {
    var _a, _b, _c, _d;
    try {
        const userId = (_a = req.user) === null || _a === void 0 ? void 0 : _a.uid;
        if (!userId) {
            res.status(401).json({ error: 'Unauthorized: No user ID provided' });
            return;
        }
        // Verify user exists
        const user = await (0, userModel_1.getUser)(userId);
        if (!user) {
            res.status(404).json({ error: 'User not found. Please register or log in first.' });
            return;
        }
        console.log('User verified:', { uid: userId, email: user.email, displayName: user.displayName || 'N/A' });
        // Get cart items for the user
        const cartItems = await (0, cartModel_1.getCart)(userId);
        if (!cartItems || cartItems.length === 0) {
            res.status(400).json({ error: 'Cart is empty. Add items to your cart before creating an order.' });
            return;
        }
        console.log('Cart items retrieved:', cartItems);
        // Map cart items to order items and fetch product prices
        const orderItems = await Promise.all(cartItems.map(async (item) => {
            const productQuery = 'SELECT price FROM products WHERE id = $1';
            const productResult = await dbConnection_1.default.query(productQuery, [item.productId]);
            if (productResult.rows.length === 0) {
                throw new Error(`Product ${item.productId} not found in products table`);
            }
            return {
                id: 0, // Placeholder, as id will be generated by the database
                orderId: 0, // Placeholder, as orderId will be set after order creation
                productId: item.productId,
                quantity: item.quantity,
                price: productResult.rows[0].price,
            };
        }));
        console.log('Order items prepared:', orderItems);
        // Create the order
        const order = await (0, orderModel_1.createOrder)(userId, orderItems);
        console.log('Order created:', order);
        // Clear the cart
        await dbConnection_1.default.query('DELETE FROM cart WHERE user_id = $1', [userId]);
        console.log('Cart cleared for user:', userId);
        res.status(201).json({ success: true, order });
    }
    catch (error) {
        console.error('Create order error:', {
            message: error.message,
            stack: error.stack,
            code: error.code,
            detail: error.detail,
            userId: (_b = req.user) === null || _b === void 0 ? void 0 : _b.uid,
            cartItems: (await (0, cartModel_1.getCart)(((_c = req.user) === null || _c === void 0 ? void 0 : _c.uid) || '')).length || 'Not retrieved',
            orderItemsAttempted: (await Promise.all((await (0, cartModel_1.getCart)(((_d = req.user) === null || _d === void 0 ? void 0 : _d.uid) || '')).map(async (item) => {
                var _a;
                return ({
                    productId: item.productId,
                    quantity: item.quantity,
                    price: ((_a = (await dbConnection_1.default.query('SELECT price FROM products WHERE id = $1', [item.productId])).rows[0]) === null || _a === void 0 ? void 0 : _a.price) || 0,
                });
            }))) || 'Not retrieved',
        });
        if (error.code === '23503') { // Foreign key violation
            res.status(400).json({
                error: 'Invalid user or product reference. Ensure user and products exist.',
                details: 'Foreign key violation occurred, likely due to missing user or product.'
            });
            return;
        }
        if (error.message.includes('Product')) { // Custom product not found error
            res.status(400).json({ error: error.message });
            return;
        }
        if (error.code === '23505') { // Duplicate key violation (e.g., order already exists)
            res.status(409).json({
                error: 'Order creation conflict. An order may already exist for these items.',
                details: error.detail
            });
            return;
        }
        res.status(500).json({
            error: 'Failed to create order',
            details: error.message || 'Unknown error',
            code: error.code,
            detail: error.detail
        });
    }
};
exports.createOrderHandler = createOrderHandler;
/**
 * Retrieves a specific order by ID for the authenticated user.
 * @param req Request object with order ID parameter
 * @param res Response object to send the order data
 * @param next Next function for error handling
 */
const getOrderHandler = async (req, res, next) => {
    try {
        const orderId = parseInt(req.params.id, 10);
        if (isNaN(orderId)) {
            res.status(400).json({ error: 'Invalid order ID' });
            return;
        }
        const orderData = await (0, orderModel_1.getOrder)(orderId);
        if (!orderData) {
            res.status(404).json({ error: 'Order not found' });
            return;
        }
        res.status(200).json({ success: true, order: orderData.order, items: orderData.items });
    }
    catch (error) {
        console.error('Get order error:', error);
        next(error);
    }
};
exports.getOrderHandler = getOrderHandler;
/**
 * Lists all orders for the authenticated user.
 * @param req Request object with authenticated user ID
 * @param res Response object to send the list of orders
 * @param next Next function for error handling
 */
const listOrdersHandler = async (req, res, next) => {
    var _a;
    try {
        const userId = (_a = req.user) === null || _a === void 0 ? void 0 : _a.uid;
        if (!userId) {
            res.status(401).json({ error: 'Unauthorized: No user ID provided' });
            return;
        }
        const orders = await (0, orderModel_1.listOrdersByUser)(userId);
        res.status(200).json({ success: true, orders });
    }
    catch (error) {
        console.error('List orders error:', error);
        next(error);
    }
};
exports.listOrdersHandler = listOrdersHandler;
