// src/controllers/orderController.ts
import { Request, Response, NextFunction } from 'express';
import { createOrder, getOrder, listOrdersByUser, Order, OrderItem } from '../models/orderModel';
import { getCart } from '../models/cartModel';
import { getUser } from '../models/userModel';
import pool from '../utils/dbConnection';

declare module 'express' {
  interface Request {
    user?: { uid: string };
  }
}

/**
 * Handles creating an order from the user's cart.
 * @param req Request object with authenticated user ID
 * @param res Response object to send the order data
 * @param next Next function for error handling
 */
export const createOrderHandler = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const userId = req.user?.uid;
    if (!userId) {
      res.status(401).json({ error: 'Unauthorized: No user ID provided' });
      return;
    }

    // Verify user exists
    const user = await getUser(userId);
    if (!user) {
      res.status(404).json({ error: 'User not found. Please register or log in first.' });
      return;
    }

    console.log('User verified:', { uid: userId, email: user.email, displayName: user.displayName || 'N/A' });

    // Get cart items for the user
    const cartItems = await getCart(userId);
    if (!cartItems || cartItems.length === 0) {
      res.status(400).json({ error: 'Cart is empty. Add items to your cart before creating an order.' });
      return;
    }

    console.log('Cart items retrieved:', cartItems);

    // Map cart items to order items and fetch product prices
    const orderItems: OrderItem[] = await Promise.all(
      cartItems.map(async (item) => {
        const productQuery = 'SELECT price FROM products WHERE id = $1';
        const productResult = await pool.query(productQuery, [item.productId]);
        if (productResult.rows.length === 0) {
          throw new Error(`Product ${item.productId} not found in products table`);
        }
        return {
          id: 0, // Placeholder, as id will be generated by the database
          orderId: 0, // Placeholder, as orderId will be set after order creation
          productId: item.productId,
          quantity: item.quantity,
          price: productResult.rows[0].price,
        };
      })
    );

    console.log('Order items prepared:', orderItems);

    // Create the order
    const order = await createOrder(userId, orderItems);
    console.log('Order created:', order);

    // Clear the cart
    await pool.query('DELETE FROM cart WHERE user_id = $1', [userId]);
    console.log('Cart cleared for user:', userId);

    res.status(201).json({ success: true, order });
  } catch (error: any) {
    console.error('Create order error:', {
      message: error.message,
      stack: error.stack,
      code: error.code,
      detail: error.detail,
      userId: req.user?.uid,
      cartItems: (await getCart(req.user?.uid || '')).length || 'Not retrieved',
      orderItemsAttempted: (await Promise.all(
        (await getCart(req.user?.uid || '')).map(async (item) => ({
          productId: item.productId,
          quantity: item.quantity,
          price: (await pool.query('SELECT price FROM products WHERE id = $1', [item.productId])).rows[0]?.price || 0,
        }))
      )) || 'Not retrieved',
    });
    if (error.code === '23503') { // Foreign key violation
      res.status(400).json({ 
        error: 'Invalid user or product reference. Ensure user and products exist.', 
        details: 'Foreign key violation occurred, likely due to missing user or product.' 
      });
      return;
    }
    if (error.message.includes('Product')) { // Custom product not found error
      res.status(400).json({ error: error.message });
      return;
    }
    if (error.code === '23505') { // Duplicate key violation (e.g., order already exists)
      res.status(409).json({ 
        error: 'Order creation conflict. An order may already exist for these items.', 
        details: error.detail 
      });
      return;
    }
    res.status(500).json({ 
      error: 'Failed to create order', 
      details: error.message || 'Unknown error', 
      code: error.code,
      detail: error.detail 
    });
  }
};

/**
 * Retrieves a specific order by ID for the authenticated user.
 * @param req Request object with order ID parameter
 * @param res Response object to send the order data
 * @param next Next function for error handling
 */
export const getOrderHandler = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const orderId = parseInt(req.params.id, 10);
    if (isNaN(orderId)) {
      res.status(400).json({ error: 'Invalid order ID' });
      return;
    }
    const orderData = await getOrder(orderId);
    if (!orderData) {
      res.status(404).json({ error: 'Order not found' });
      return;
    }
    res.status(200).json({ success: true, order: orderData.order, items: orderData.items });
  } catch (error) {
    console.error('Get order error:', error);
    next(error);
  }
};

/**
 * Lists all orders for the authenticated user.
 * @param req Request object with authenticated user ID
 * @param res Response object to send the list of orders
 * @param next Next function for error handling
 */
export const listOrdersHandler = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const userId = req.user?.uid;
    if (!userId) {
      res.status(401).json({ error: 'Unauthorized: No user ID provided' });
      return;
    }
    const orders = await listOrdersByUser(userId);
    res.status(200).json({ success: true, orders });
  } catch (error) {
    console.error('List orders error:', error);
    next(error);
  }
};